apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: name
  name: name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: name
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: name
    spec:
      containers:
      - image: image
        name: name
        resources: {}
status: {}
